pipeline{
    
    agent {
    label 'eng110-jenkins-worker'
    }

    parameters {
      booleanParam defaultValue: false, description: 'Initialise the Kubernetes cluster?', name: 'Initialise'
      booleanParam defaultValue: true, description: 'Run rolling updates?', name: 'Rolling'
    }

    stages {
        stage('Checkout') {
            steps {
                 script{
                        dir("ansible"){
                            checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/samuel-walters/Complete-CICD']]])
                        }
                    }
                }
            }
      
        stage("Run an ansible playbook"){
            steps{
                script {
                    dir("ansible/ansible_playbooks"){
                        withCredentials([file(credentialsId: 'AnsiblePasswordForVaultFile', variable: 'PasswordFile')]) {
                            if (params.Initialise == true) {
                                echo "Initialising the Kubernetes Cluster"
                                sh 'sudo ansible-playbook run_playbooks.yml --vault-password-file ${PasswordFile}'
                            }
                            if (params.Rolling == true) {
                                echo "Running a rolling update"
                                sh 'sudo ansible-playbook kubernetes_rolling_updates.yml --vault-password-file ${PasswordFile}'
                            }
                        }
                    }
                }
            }
        }
    }
}