---
 - hosts: controlplane
   become: yes
   become_method: sudo
   become_user: root
   tasks:

   - name: Running a rolling update command
     shell: |
       kubectl set image deployments/eng110-node-deployment node=samuelwalters/app:latest