---
 - hosts: controlplane
   become: yes
   become_method: sudo
   become_user: root
   tasks:

   - name: delete rolling_update.txt if it exists
     file:
       path: /root/rolling_update.txt
       state: absent

   - name: create new rolling_update.txt file
     copy: src=/home/jenkins/rolling_update.txt dest=/root/rolling_update.txt

   - name: run rolling update command
     shell: |
       bash /root/rolling_update.txt
     environment:
       KUBECONFIG: /etc/kubernetes/admin.conf